# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qlWIRIJhR6Vd8+Sxhjyir94bCfgvwfYSFOxH40dvCT+303Qj4ws2EW9iHJabuVuO10JIBipSAKsI+qdmQ4QbcfQobSpTLTguYHFEXZS9QRgRk26OCyZMUQmKJr44XYiNVY0oI8MV23uo3tUJs0wcj0qlShRmficXUll68MTe8UEJQgY9QP58jVVjjcYSn4FxwsnrJ8zKM9CIJkbw57xcC/o0dGzSe/BzNpOx8DOMA24eUEkcERTfG3l1TLLGAjXH37VdNN2WhOVHcGECJHc9xha+aIrEpLURFXURCGFvscZiYcrMVDSSBdMSGHvUXmhu7G3CsojcMv1wNbzp8isjkqeDYp38DYiKE04E32kIyd09k7ciX9VeIH0ZmFly6TdKbjAP+KSLBeA+ruChwZxYwAPCXjnkm2X1KfNHhTx1WJivjLGm1VVO7ACh3EKeKq7oSVxn2CsfcWswSwEHNSsSmyd5O68hKs7leiHEP8UEVMBr9xwMJdOOP3rwr2py7PzyukdbsGhaQLM5d2h22Li9E6hwHSxP4ysLs8QgPRmfGnHB65OKhdR/MJddweE64JWSCbs0/KODp/ZA9OZQbFtEtPwY32SkIsXCiVv+mKI1UmEvOXvJ6Uo6QylOLJFE9alcDHraeTsIZQlK+jVLogPyK4442XVu8khLAQ2YWxkJrNw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
