travis:
  secure:
    BINSTAR_TOKEN: RVI+ljdtMTCrAFp0cSpxkUdRH5uw8Zbp4ZOhyPOp+Ng2zNb2bx1Yj2ou34+m9DTn1kxV20+BL08dhBlgjoIGBkQNeaUevTefRaLZrrQSq7I53ysZDTcozQe8XftCQX7Y/nP5u5ekT3llXItSfGqkVNAoE0hisQmUOWSYnbS4SL9nOvrSX5aAdGtqXJf3HeN7r+iGnRTlm60Sz7nD/M7rrx0/zqejL2dUDvfP1UkRd4Iil9taPtVLtwP/u+RUcLvZCzSm+KxF6LpBy+fSZZ29VwfVkIroV0SMzf1Ei0xCoPlqp7Co1rcf9/JebMuZwU1GFwu9nRCljO0PP8e8Yg6cFQR/1uRDCrSVz9sKHAneb6nMVoYc7KydimskDbELPtiQi7WlwCoTA9szW5NMbA/7xBotOWUhf+x6cIoL7Iif9yJyHOMNjxxrwqpnTelUwPswbYqbEIaEVPHPfrU60S/Mh9Bez3ThFd7xdMuxQCILTnSLnnLA8dwMTVgzwsa5HML1pTgDOIzOQ7+MvjMD0ap9O/S/Tv07DIttIsT2CFgrvtuUj4xH1SypYJeAx0WiXPjcCtlT9rbK17kXGe1QxZ8RC80y9C0ILwkE/ro4Igyd27S9tMFd3L+NQQnMqLFstc24YGpmwkMqg0lCX5NQYDO2qFBjTh/0QYYvHA9hmywLMwI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
