travis:
  secure:
    BINSTAR_TOKEN: qlWIRIJhR6Vd8+Sxhjyir94bCfgvwfYSFOxH40dvCT+303Qj4ws2EW9iHJabuVuO10JIBipSAKsI+qdmQ4QbcfQobSpTLTguYHFEXZS9QRgRk26OCyZMUQmKJr44XYiNVY0oI8MV23uo3tUJs0wcj0qlShRmficXUll68MTe8UEJQgY9QP58jVVjjcYSn4FxwsnrJ8zKM9CIJkbw57xcC/o0dGzSe/BzNpOx8DOMA24eUEkcERTfG3l1TLLGAjXH37VdNN2WhOVHcGECJHc9xha+aIrEpLURFXURCGFvscZiYcrMVDSSBdMSGHvUXmhu7G3CsojcMv1wNbzp8isjkqeDYp38DYiKE04E32kIyd09k7ciX9VeIH0ZmFly6TdKbjAP+KSLBeA+ruChwZxYwAPCXjnkm2X1KfNHhTx1WJivjLGm1VVO7ACh3EKeKq7oSVxn2CsfcWswSwEHNSsSmyd5O68hKs7leiHEP8UEVMBr9xwMJdOOP3rwr2py7PzyukdbsGhaQLM5d2h22Li9E6hwHSxP4ysLs8QgPRmfGnHB65OKhdR/MJddweE64JWSCbs0/KODp/ZA9OZQbFtEtPwY32SkIsXCiVv+mKI1UmEvOXvJ6Uo6QylOLJFE9alcDHraeTsIZQlK+jVLogPyK4442XVu8khLAQ2YWxkJrNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
